AsahiLinux/muvm

crates/krun/Cargo.toml
crates/krun/src/bin/krun.rs
crates/krun/src/net.rs

Use std::os::unix::net::UnixStream::pair instead of rustix::net::socketpair

---

crates/krun-guest/Cargo.toml
crates/krun-guest/src/bin/krun-guest.rs

This is required for wine's esync to work.

Raise RLIMIT_NOFILE in krun-guest

---

Cargo.lock
crates/krun-guest/src/bin/krun-guest.rs
crates/krun-guest/src/lib.rs
crates/krun-guest/src/pulse.rs
crates/krun-guest/src/user.rs
crates/krun/src/bin/krun.rs

If $XDG_RUNTIME_DIR/pulse/native and /usr/bin/socat exist in the system,
configure a vsock device pointing to the former and use the latter to
act as a unix-socket to vsock proxy.
This enables applications in the guest to access the pulseaudio socket
in the host.

host-guest: create a proxy for the pulse socket

---

Cargo.lock
Cargo.toml
crates/krun-server/Cargo.toml
crates/krun-server/src/bin/krun-server.rs
crates/krun-server/src/cli_options.rs
crates/krun-server/src/lib.rs
crates/krun-server/src/server.rs
crates/krun/src/bin/krun.rs
crates/krun/src/cli_options.rs
crates/krun/src/lib.rs
crates/krun/src/lock.rs
crates/krun/src/net.rs
crates/utils/Cargo.toml
crates/utils/src/env.rs
crates/utils/src/launch.rs
crates/utils/src/lib.rs

With the introduction of 47fdd45a (Default guest memory to 80% of total RAM on host), we're targeting a use case in which we expect to be running a single, large VM.
To accommodate this use case, we're switching here to a client/server model. The first time krun is launched, in addition to running the command, it starts a small server in the VM listening on a TCP port. On the host side, it also creates a lock file, writes the listening port number to it, and calls flock() on it to prevent other instances from running in parallel.
When it's executed again, krun detects there's another instance running, and contacts the server in the VM to request the launch of the command. The stdout and stderr of the command are redirected to $XDG_RUNTIME_DIR/krun-$COMMAND-$TIMESTAMP.[stdout|stderr]

Introduce a client-server model

---

crates/krun/src/bin/krun.rs
crates/krun/src/cli_options.rs
crates/krun/src/types.rs

The use case targeted by krun is not compatible with TSI networking, so  drop it as an option to avoid unnecessary confusion.

Drop support for TSI networking

---

crates/krun-server/src/bin/krun-server.rs

Listening on 127.0.0.1 doesn't allow passt to forward incoming connections.
Fixes #29

server: listen on any interface

---

Cargo.lock
Cargo.toml
crates/krun-guest/src/net.rs
crates/krun-guest/src/pulse.rs
crates/krun-server/Cargo.toml
crates/krun-server/src/bin/krun-server.rs
crates/krun-server/src/server.rs
rustfmt.toml

Continue to accept and handle incoming connections, until the server is idle and all child processes have exited.
Fixes #33
Tested working with all of the scenarios mentioned in the linked issue, and confirmed that the server exits correctly once all the child processes have exited (doesn't seem to run into deadlocks).

Make krun-server wait for child processes

---

crates/krun/src/env.rs

This avoids having to explicitly list all current and future devices.

env: Use generic apple,arm-platform compatible to check for Apple SoCs

---

Cargo.lock
Cargo.toml
crates/krun-guest/Cargo.toml
crates/krun-guest/src/bin/krun-guest.rs
crates/krun-guest/src/lib.rs
crates/krun-guest/src/mount.rs
crates/krun-guest/src/socket.rs
crates/krun-guest/src/x11.rs
crates/krun/src/bin/krun.rs
crates/krun/src/env.rs

If the host has DISPLAY set, parse it and forward that UNIX socket to the guest via vsock, then forward :1 on the guest to this vsock, and finally set HOST_DISPLAY=:1 on the guest.
Apps that want to directly talk to X11 on the host (instead of going through sommelier) should set DISPLAY=$HOST_DISPLAY and LIBGL_ALWAYS_SOFTWARE=true. This setup allows X11 apps in the host and the guest to cooperate (e.g. XEmbed) but requires software rendering inside the guest.
TODO: Figure out why things hang without LIGL_ALWAYS_SOFTWARE=true. Ideally DRI3 should fail and fall back to software automatically.

Support native X11 forwarding

---

Cargo.lock
Cargo.toml
crates/krun-guest/src/mount.rs
crates/krun-guest/src/socket.rs
crates/krun-guest/src/x11.rs
crates/krun/src/bin/krun.rs
crates/krun/src/net.rs
crates/utils/Cargo.toml
crates/utils/src/stdio.rs

It's too easy to hit the same millisecond...
Example of error message:
```
Error: File exists (os error 17)
```

Use uuidv7 for stdout / stderr files

---

crates/krun/src/bin/krun.rs
crates/krun/src/cli_options.rs
crates/krun/src/guest/mount.rs

This adds a mechanism for automatically managing the FEX rootfs, mounting and overlayfs'ing the relevant squashfs files from the host.
Depends on:
* libkrun https://github.com/containers/libkrun/pull/217
* libkrunfw https://github.com/containers/libkrunfw/pull/65

Automatically manage FEX rootfs

---

crates/krun/src/guest/net.rs

By default, the kernel doesn't allow unprivileged users to create ICMP Echo sockets, which can lead to confusing messages like this one:
$ ping 1.1.1.1
ping: socktype: SOCK_DGRAM
ping: socket: Address family not supported by protocol
Most distros adjust "ipv4/ping_group_range" to allow unprivileged users to use "ping" without relying on setuid, so do the same for krun guests.

guest: allow unprivileged users to use ping

---

crates/krun/src/guest/sommelier.rs

With HiDPI screens, some games running in sommelier may scale way beyond the actual screen size. Passing --direct-scale to sommelier fixes this.
While there, also pass --log-level=3 to reduce sommelier's verbosity which was increased in the latest versions.

Pass --direct-scale and --log-level to sommelier

---

crates/krun/src/bin/krun.rs
crates/krun/src/env.rs

When using "krun_set_exec", the arguments and environment variables are passed to the guest using the kernel command line. In addition to being limited in length, this is also only compatible with ASCII strings.
libkrun is also capable or reading both arguments and environment variables from a JSON config file, which doesn't suffer from any of those limitations, so switch to using this approach instead.
Depends on https://github.com/containers/libkrun/pull/220

Pass args and envs using a config file

---

crates/krun/src/guest/mount.rs

These dirs may not exist depending how fex-emu was installed.

Allow fex-emu config to fail

---

crates/krun/src/bin/krun.rs

With https://pagure.io/fedora-asahi/mesa/pull-request/21 the mesa overlay is splitted into i386 and x86_64 as they are generated during the main mesa build.

Split FEX mesa overlay into i386 and x86_64 overlays

---

crates/krun/src/bin/krun.rs
crates/krun/src/cli_options.rs

Starting v1.9.5, libkrun allows configuring the size of the SHM window
for virtio-gpu, which acts as a pseudo-vram (previously it was hardcoded
to a conservative 8GB).
Let's use that feature to configure the vRAM of the microVM to a
reasonable value. Since we expect userspace drivers in the guest to be
conservative for us, telling appliations that vRAM is just a percentage
of the guest's RAM, let's just set vRAM to be the same as the total
amount of RAM in the system, leaving some room for potential
fragmentation.
Also, introduce the "--vram" command flag to allow users to override the
default value.
While there, also remove the 32 GB limit, since libkrun does support
guests larger than that.

krun: set the vRAM size for the microVM

---

crates/muvm/src/guest/net.rs

The error handled in #74 was muvm-guest's network code. So fixing it there directly. Not sure if any of the actual binaries running in the guest actually care about `/etc/hostname`.

guest/net: Handle missing /etc/hostname gracefully

---

crates/muvm/src/guest/mount.rs

The change apparently doesn't work and the know issue was in muvm itself fixed by commit c9b574d ("guest/net: Handle missing /etc/hostname gracefully").
This reverts commit 29e77d2c657f1c14cbe063657a7def39fcca6f7b.

Revert "guest: set an /etc/hostname if we don't have one"

---

crates/muvm/src/guest/mount.rs

On Asahi Gentoo the FEX rootfs is a part of the host filesystem, and as such the muvm image mount mechanism is not used. Skip overmounting the FEX directory in that case.

Do not clobber FEX config if no images were mounted.

---

Cargo.lock
crates/muvm/Cargo.toml

This is a minor hotfix release to deal with the /etc/hostname issue.

muvm: Bump version to 0.1.3

---

crates/muvm/Cargo.toml
crates/muvm/src/guest/bin/muvm-guest.rs

This fixes the classic:
-bash: cannot set terminal process group (-1): Inappropriate ioctl for device
-bash: no job control in this shell
I'm not entirely sure why this doesn't happen with our main shell, but it happens with things like sudo. (There are a bunch of other things needed to make sudo work, of course)

muvm-guest: Reopen the system tty (hvc0)

---

crates/muvm/src/bin/muvm.rs
crates/muvm/src/cli_options.rs
crates/muvm/src/env.rs
crates/muvm/src/guest/bin/muvm-guest.rs
crates/muvm/src/guest/x11.rs

Replace the trivial X11 socket passthrough with x112virtgpu, if it is installed and DAX is enabled. This lives alongside the existing sommelier solution, so we can test both options for now.

Basic x112virtgpu support

---

Cargo.lock
crates/muvm/Cargo.toml
crates/muvm/src/bin/muvm.rs
crates/muvm/src/cli_options.rs
crates/muvm/src/guest/bin/muvm-guest.rs
crates/muvm/src/launch.rs
crates/muvm/src/lib.rs
crates/muvm/src/monitor.rs
crates/muvm/src/net.rs
crates/muvm/src/server/bin/muvm-server.rs
crates/muvm/src/server/worker.rs
crates/muvm/src/utils/launch.rs

The goal of this PR is to enable muvm to request the guest to adjust its file system cache goals accordingly to the amount of available memory on the host.
The first two commits just set the infrastructure, first by adding some minimal protection to muvm-server, and then spawning a second instance of it as root (we need this to operate in "/proc/sys/vm", but surely will come handy for many other things).
The latter implements the monitor and the ability to request the guest to adjust watermark_scale_factor as needed, or even to drop its pagecache if the situation is critical.

Protect muvm-server, spawn one as root and monitor available host memory

---

crates/muvm/src/x11bridge/bin/muvm-x11bridge.rs

1.4 introduced syncobj support, and we do not support those yet

x11bridge: Downgrade DRI3 to 1.3

---

crates/muvm/src/bin/muvm.rs
crates/muvm/src/cli_options.rs

By default, HK sets the heap size to be half the size of the *guest*
memory. Since commit 167744dc it's also possible to override the heap
size by setting the HK_SYSMEM environment variable.
Previously, the vram command line option was acting on the virtio-gpu
SHM window. This didn't help in most cases because userspace doesn't
really care nor is aware of it.
Here, we set the SHM window of virtio-gpu to always be as large as the
host's RAM, not because we expect VRAM to consume 100% of the RAM (which
is obviously impossible) but to account for region fragmentation. Then,
we use HK_SYSMEM to tell userspace the desired heap size (the closest
thing to VRAM we can aim for), which will be set to either the value
passed by the user throught the "vram" argument or half the size of the
*host* …

Improve VRAM management in the guest

---

.github/workflows/code_quality.yml
Cargo.lock
crates/muvm/Cargo.toml
crates/muvm/src/bin/muvm.rs
crates/muvm/src/guest/bin/muvm-guest.rs
crates/muvm/src/hidpipe/bin/muvm-hidpipe.rs
crates/muvm/src/hidpipe_common.rs
crates/muvm/src/hidpipe_server.rs
crates/muvm/src/lib.rs

Merge hidpipe project into muvm, with hidpipe-server operating as a thread inside the main muvm binary, and hidpipe-client getting renamed to muvm-hidpipe (and it's still autostarted by muvm-guest).
This simplifies the lifecycle management for hidpipe, ensuring it's tied to the microVM lifetime.
Co-developed-by: Sasha Finkelstein <fnkl.kernel@gmail.com>

hidpipe: merge hidpipe project into muvm

---

crates/muvm/src/bin/muvm.rs
crates/muvm/src/env.rs
crates/muvm/src/guest/bin/muvm-guest.rs

Otherwise this depends on where you run things from. In my case, I
would get:
$ ./target/debug/muvm -- /bin/false
Error: Failed to execute `muvm-server` as child process
Caused by:
No such file or directory (os error 2)
Signed-off-by: Stefano Brivio <sbrivio@redhat.com>

muvm-guest: Find actual path for muvm-server before trying to execute it

---

crates/muvm/src/bin/muvm.rs
crates/muvm/src/cli_options.rs
crates/muvm/src/launch.rs

After launching a process via the server, krun immediately closes and the
launched process' std{in,out,err} go nowhere. Add a --interactive flag that
allocates a pseudo-terminal, routes it to the host and connects to it.
Somewhat like '-it' in docker/podman exec.

Add interactive launch mode.

---

.gitignore
Cargo.lock
crates/muvm/Cargo.toml
crates/muvm/src/bin/muvm.rs
crates/muvm/src/cli_options.rs
crates/muvm/src/launch.rs
crates/muvm/src/lib.rs
crates/muvm/src/monitor.rs
crates/muvm/src/server/worker.rs
crates/muvm/src/tty.rs
crates/muvm/src/utils/launch.rs
crates/muvm/src/utils/mod.rs
crates/muvm/src/utils/tty.rs

Socat's tty mode has issues with window resizing
as it does not pass through SIGWINCH. Also add
a tty-less interactive mode, for usage from scripts and similar.

muvm: Replace socat for interactive mode.

---

crates/muvm/src/bin/muvm.rs

Now that muvm is able to request the guest to decrease its file cache and the root cause for the premature OOM has been indentified, let's remove the check for 8GB machines that limited the microVM to be smaller than 5GB, and just set it to be 80% of the host RAM, just as we do with systems with other configurations.
In practice, this enables 8GB machines to run more games out of the box (tested with multiple Steam games on a MacBook Air M1 with 8GB).

muvm: remove RAM special case for 8GB machines

---

crates/muvm/src/guest/x11.rs

Apparently GNOME does this (empty display field)...

x11: Fix XAUTHORITY handling for wildcard DISPLAY

---

crates/muvm/src/bin/muvm.rs
crates/muvm/src/cli_options.rs
crates/muvm/src/guest/mount.rs

In this mode, the FEX rootfs passed to FEX is already overlaid on top of the real root filesystem, so FEX directs all guest accesses to it instead of doing its own overlay logic. This, together with a bunch of fixes on the FEX side, fixes Wine.
Opt-in for now, since this actively *breaks* things with the current FEX. May become the default in the future once all that is sorted out.
The FEX config option name is speculative since it doesn't exist yet and it isn't strictly required to tell FEX about this, but I'd rather have it in to be able to change the logic on the FEX side in this mode as needed.

mount: Add support for FEX merged rootfs mode

---

crates/muvm/src/bin/muvm.rs
crates/muvm/src/cli_options.rs
crates/muvm/src/guest/bin/muvm-guest.rs
crates/muvm/src/guest/hidpipe.rs
crates/muvm/src/guest/server.rs
crates/muvm/src/guest/server_worker.rs
crates/muvm/src/guest/socket.rs
crates/muvm/src/launch.rs
crates/muvm/src/monitor.rs
crates/muvm/src/net.rs
crates/muvm/src/utils/launch.rs

Add an ability to configure the set of published ports via command line switches. 
This is a continuation from #134 that moves all internal communications to vsock ports.

Port passthrough

---

crates/muvm/src/bin/muvm.rs
crates/muvm/src/cli_options.rs
crates/muvm/src/guest/bin/muvm-guest.rs
crates/muvm/src/guest/box64.rs
crates/muvm/src/guest/fex.rs
crates/muvm/src/guest/mod.rs
crates/muvm/src/utils/launch.rs

Add the "emu" command line argument to let users choose the emulator to be used for running x86 binaries. Add support for installing Box64 in binfmt_misc. If the argument is not present in the command line, try to use FEX first and if it can't be set up, try again with Box64.
Supersedes: #140

Support using Box64 for x86 emulation

---

.github/workflows/code_quality.yml
Cargo.lock
crates/krun-sys/Cargo.toml
crates/krun-sys/build.rs

This enables the use of non-system-wide installations of libkrun by exporting the right PKG_CONFIG_PATH.

krun-sys: find libkrun using pkg-config

---

crates/muvm/src/guest/mount.rs

Otherwise we get fun stuff like:
```
overlay on /run/fex-emu/rootfs type overlay (ro,relatime,lowerdir=/run/fex-emu/vda:/run/fex-emu/vdb:/run/fex-emu/vdc,redirect_dir=on)
```
-> which means there's no `/run/fex-emu/rootfs/lib{,64}/dri/{apple,asahi}_dri.so` when running on Fedora Asahi Remix 42 beta
-> which causes Steam to fail to launch with error messages such as:
```
[2025-03-28 01:18:26] glx: failed to create dri3 screen
[2025-03-28 01:18:26] failed to load driver: asahi
[2025-03-28 01:18:26] 03/28 01:18:26 Failed writing minidump, nothing to upload.
[2025-03-28 01:18:26] /home/teohhanhui/.local/share/Steam/steam.sh: line 949:   381 Segmentation fault      "$STEAMROOT/$STEAMEXEPATH" "$@"
```

Fix ordering of erofs images in overlay fs

---

README.md
crates/muvm/src/bin/muvm.rs
crates/muvm/src/cli_options.rs
crates/muvm/src/config.rs
crates/muvm/src/guest/bin/muvm-guest.rs
crates/muvm/src/guest/user.rs
crates/muvm/src/lib.rs
crates/muvm/src/utils/launch.rs

Closes #37, supersedes #38 while being more general
Allows to execute a command before the guest server starts.
Useful on distros like NixOS where we need additional mounts.
E.g. on NixOS this means I can use muvm from main with this patch by running `muvm --init-command=init.sh $SHELL` with `init.sh` being
```sh
#!/bin/sh
ln -s /run/muvm-host/run/opengl-driver /run/opengl-driver
ln -s /run/muvm-host/run/current-system /run/current-system
```
whereas currently it's not as straightforward

Add init-command option

---

crates/muvm/src/guest/net.rs

Up until now DHCP response was parsed by reading the option and the length first. The length field obviously does not apply to the End option, so if muvm got a response that ended exactly at the End byte, muvm would crash because of an out-of-bound read.
This works with older versions of passt because the response muvm received was longer than it could've been. Latest version of passt sends only as many bytes as necessary.
cc @sbrivio-rh

Return early from parsing DHCP response if End is encoutered

---

Cargo.lock
crates/muvm/Cargo.toml

Prepare for an expedited minor release to address a crash when parsing a DHCP response from passt (see #168).

Bump version 0.4.1

---

crates/muvm/src/guest/user.rs

The current behavior seems to date back to the initial commit of the original C version of this tool:
https://github.com/teohhanhui/krun.legacy/commit/01ae759737f4056977c26e269978c670fd13e918#diff-ba1f55157a5e8661da39884a2669de7c912ff94d98134d6d520ed0468670e39bR198
Is anything relying on this extra permissiveness? I didn't notice any breakage in a quick test after patching this (consisting of launching Balatro through steam, nevermind that I normally just use the native build of love to run balatro) but that doesn't mean much.

Set XDG_RUNTIME_DIR perimssions to 700

---

crates/muvm/src/guest/bridge/common.rs
crates/muvm/src/guest/bridge/pipewire.rs
crates/muvm/src/guest/bridge/x11.rs
crates/muvm/src/hidpipe_server.rs
crates/muvm/src/net.rs

Linux version of Dota 2 includes a new enough version of SDL to have native pipewire support. Naturally it ends up using protocol features that the bridge did not support previously

Improved pipewire bridge support

---

crates/muvm/src/guest/bridge/common.rs
crates/muvm/src/guest/bridge/pipewire.rs
crates/muvm/src/guest/bridge/x11.rs
crates/muvm/src/hidpipe_server.rs
crates/muvm/src/net.rs

Truncated messages are just a fact of life, we handle them correctly. Same for clients disconnecting with ECONNRESET, both were useful debug aids, but now they are just useless spam that can look like an error to an unknowing user.

Reduce bridge spamminess
